/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tatamimanager.colegios;

import com.mycompany.tatamimanager.BBDD.DatabaseManager;
import com.mycompany.tatamimanager.BBDD.DataBaseControlColegios;
import com.mycompany.tatamimanager.Inicio;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author diana
 */
public class AddColegios extends javax.swing.JPanel {

    private String nombreCole;
    private String direccionCole;
    private int telefonoCole; 
    private String barrioCole;
    private int cpCole; 
    private int id; 
    public boolean isUpdate = false;
        
    /**
     * Creates new form AddColegio
     */
    public AddColegios() {
        initComponents();
    }
    
    public boolean validarDatos(){
        // Verificar si los campos están vacíos
        if (txt_nombre.getText().trim().isEmpty() || txt_direccion.getText().trim().isEmpty() || txt_telf.getText().trim().isEmpty() || 
            txt_barrio.getText().trim().isEmpty() || txt_cp.getText().trim().isEmpty()) {

            // Mostrar mensaje de advertencia
            JOptionPane.showMessageDialog(null, "Por favor, rellena todos los campos.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            
            return false;

        } else {
            // Validar y asignar los valores
            nombreCole = txt_nombre.getText().trim();
            direccionCole = txt_direccion.getText().trim();
            barrioCole = txt_barrio.getText().trim();

            // Validar que el telefono sea un número y tenga 9 dígitos
            String telefono = txt_telf.getText().trim();
            if (!telefono.matches("\\d{9}")) {
                JOptionPane.showMessageDialog(null, "El teléfono debe ser un número de 9 dígitos.", "Error en el Teléfono", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            telefonoCole = Integer.parseInt(txt_telf.getText().trim()); //asignat telf

            // Validar que el CP sea un número y tenga 5 dígitos
            String cpTexto = txt_cp.getText().trim(); 
            if ( !cpTexto.matches("\\d{5}")) { 
                JOptionPane.showMessageDialog(null, "El código postal debe ser un número de 5 dígitos.", "Error en el Código Postal", JOptionPane.ERROR_MESSAGE);
                return false; // Salir del método si la validación falla
            }
            cpCole = Integer.parseInt(cpTexto); // asignar cp

            // Mensaje de éxito
            //JOptionPane.showMessageDialog(null, "Todos los datos han sido ingresados correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
        return true;
    }
    
     // Método para modificar(actualizar) los datos
    public void actualizarDatos(int idColegio, String nombre, String direccion, int telefono, String barrio, int codpostal) {
        isUpdate = true;
        id = idColegio;
        lb_titulo.setText("Modificar Colegio");
        txt_nombre.setText(nombre);
        txt_direccion.setText(direccion);
        txt_telf.setText(Integer.toString(telefono));
        txt_barrio.setText(barrio);
        txt_cp.setText(Integer.toString(codpostal));
        btn_GuardarColegio.setText("Modificar Colegio");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_barrio = new javax.swing.JLabel();
        txt_telf = new javax.swing.JTextField();
        lb_telf = new javax.swing.JLabel();
        lb_titulo = new javax.swing.JLabel();
        lb_nombreAlumno = new javax.swing.JLabel();
        lb_dir = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_barrio = new javax.swing.JTextField();
        lb_cp = new javax.swing.JLabel();
        txt_cp = new javax.swing.JTextField();
        btn_GuardarColegio = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        lb_barrio.setText("Barrio:");

        lb_telf.setText("Teléfono:");

        lb_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_titulo.setText("Añadir Colegio");

        lb_nombreAlumno.setText("Nombre:");

        lb_dir.setText("Dirección:");

        lb_cp.setText("Código Postal:");

        txt_cp.setToolTipText("");

        btn_GuardarColegio.setBackground(new java.awt.Color(0, 102, 153));
        btn_GuardarColegio.setForeground(new java.awt.Color(255, 255, 255));
        btn_GuardarColegio.setText("Guardar Colegio");
        btn_GuardarColegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarColegioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(lb_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(btn_GuardarColegio, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_nombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_cp)
                            .addComponent(lb_telf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_telf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lb_titulo)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nombreAlumno)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_dir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_telf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_barrio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_cp))
                .addGap(42, 42, 42)
                .addComponent(btn_GuardarColegio)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GuardarColegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarColegioActionPerformed
        
        if (!validarDatos()) {
            return; // Si alguna validación falla, detener la ejecución
        }
        
        if(!isUpdate){
            DataBaseControlColegios.guardarColegio(nombreCole, direccionCole, telefonoCole, barrioCole, cpCole);
            
        }else{  //update
            try (Connection conn = DatabaseManager.getConnection()) {
                
                String query = "UPDATE colegios SET nombre = ?, direccion = ?, telefono = ?, barrio = ?, cod_postal = ? "
                             + "WHERE id_colegio = ?";
                PreparedStatement st = conn.prepareStatement(query);

                // Asignar los valores de los campos de texto a la consulta
                st.setString(1, nombreCole);
                st.setString(2, direccionCole);
                st.setInt(3, telefonoCole);
                st.setString(4, barrioCole);
                st.setInt(5, cpCole);
                st.setInt(6, id); // id es el identificador del colegio que se está editando

                // Ejecutar la consulta
                int rowsUpdated = st.executeUpdate();

                // Verificar si se realizó el cambio
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "El colegio ha sido actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo actualizar el colegio.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al actualizar el colegio: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                Logger.getLogger(AddColegios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        isUpdate = false; //volvemoa a establecer isUpdate como false
        
        //cambiar panel a listaColegios
        JFrame frameInicio = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frameInicio instanceof Inicio) {
            ((Inicio) frameInicio).cambiarPanel(new ListaColegios());
        }
    }//GEN-LAST:event_btn_GuardarColegioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GuardarColegio;
    private javax.swing.JLabel lb_barrio;
    private javax.swing.JLabel lb_cp;
    private javax.swing.JLabel lb_dir;
    private javax.swing.JLabel lb_nombreAlumno;
    private javax.swing.JLabel lb_telf;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JTextField txt_barrio;
    private javax.swing.JTextField txt_cp;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telf;
    // End of variables declaration//GEN-END:variables
}
