/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tatamimanager.colegios;

import com.mycompany.tatamimanager.DatabaseManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author diana
 */
public class ListaColegios extends javax.swing.JPanel {

    Object[] cabecera;
    DefaultTableModel modelo;

    /**
     * Creates new form ListaColegios
     */
    public ListaColegios() {
        initComponents();
            
        cabecera = new Object [] {"Nombre", "Dirección", "Teléfono", "Barrio", "Código Postal", "Editar", "Eliminar"};
        
        modelo = new DefaultTableModel(cabecera, 0){ //0-> La tabla al principio no tiene columnas
            @Override
            public Class getColumnClass(int columnIndex) {
                switch(columnIndex){
                    case 2: return Integer.class;
                    case 4: return Integer.class;
                    case 5: return ImageIcon.class;
                    case 6: return ImageIcon.class;
                    default:return String.class;
                }
            }
        };
        tablaColegios.setModel(modelo);
        
        try (Connection conn = DatabaseManager.getConnection()) { // Obtiene la conexión
            // Sentencia sql
            modelo.setRowCount(0);
            PreparedStatement st = conn.prepareStatement(
                "SELECT nombre, direccion, telefono, barrio, cod_postal FROM colegios"
            );
            ResultSet resultado = st.executeQuery();

            // Cargar los iconos desde el classpath
            ImageIcon iconEditar = new ImageIcon(ListaColegios.class.getResource("/images/lapiz.png"));
            ImageIcon iconEliminar = new ImageIcon(ListaColegios.class.getResource("/images/basura.png"));

            while (resultado.next()) {
                // Agregar una nueva fila con los datos y los iconos
                modelo.addRow(new Object[] {
                    resultado.getString("nombre"), 
                    resultado.getString("direccion"),
                    resultado.getInt("telefono"),
                    resultado.getString("barrio"),
                    resultado.getInt("cod_postal"),
                    iconEditar,  // Icono para la columna "Editar"
                    iconEliminar // Icono para la columna "Eliminar"
                });
            }
            DatabaseManager.closeConnection();  //cierre de la conexión a la bbdd
            
        } catch (SQLException e) {
            Logger.getLogger(ListaColegios.class.getName()).log(Level.SEVERE, null, e);
            System.out.println("Error al conectar o ejecutar consulta a la base de datos.");
        } catch (Exception e) {
            Logger.getLogger(ListaColegios.class.getName()).log(Level.SEVERE, null, e);
            System.out.println("Error inesperado: " + e.getMessage());
        }
        
        //colocar iconos
        try {
            ImageIcon icon = new ImageIcon(ListaColegios.class.getResource("/images/retrato.png"));
            // .setIcon(icon);
        } catch (NullPointerException e) {
            System.err.println("No se pudo cargar la imagen: " + e.getMessage());
        }
        
        //ajustar tamaño columnas 
        tablaColegios.getColumnModel().getColumn(0).setPreferredWidth(120);
        tablaColegios.getColumnModel().getColumn(1).setPreferredWidth(120);
        tablaColegios.getColumnModel().getColumn(2).setPreferredWidth(5);
        tablaColegios.getColumnModel().getColumn(3).setPreferredWidth(30);
        tablaColegios.getColumnModel().getColumn(4).setPreferredWidth(10);
        tablaColegios.getColumnModel().getColumn(5).setPreferredWidth(5);
        tablaColegios.getColumnModel().getColumn(6).setPreferredWidth(5);
        
        /*
        // Aplica el renderer solo a columnas Integer
        for (int col = 0; col < tablaColegios.getColumnCount(); col++) {
            if (tablaColegios.getColumnClass(col) == Integer.class) {
                tablaColegios.getColumnModel().getColumn(col).setCellRenderer(rightRenderer);
            }
        }
        */
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaColegios = new javax.swing.JTable();
        lb_titulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tablaColegios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaColegios.setEnabled(false);
        tablaColegios.getTableHeader().setReorderingAllowed(false);
        tablaColegios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaColegiosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaColegios);
        if (tablaColegios.getColumnModel().getColumnCount() > 0) {
            tablaColegios.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablaColegios.getColumnModel().getColumn(1).setPreferredWidth(60);
            tablaColegios.getColumnModel().getColumn(2).setPreferredWidth(20);
            tablaColegios.getColumnModel().getColumn(3).setPreferredWidth(30);
            tablaColegios.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        lb_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_titulo.setText("Listado de Colegios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(lb_titulo)
                .addContainerGap(487, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lb_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaColegiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaColegiosMouseClicked
        // Verificar si se hizo doble clic
        if (evt.getClickCount() == 2) {
            // Obtener la fila y columna donde ocurrió el clic
            int fila = tablaColegios.rowAtPoint(evt.getPoint());
            int columna = tablaColegios.columnAtPoint(evt.getPoint());

            // Verificar si se hizo clic en la columna "Editar" (columna 5)
            if (columna == 5) { 
                // Obtener el valor de la columna "nombre" (columna 0) de la fila seleccionada
                String nombreColegio = modelo.getValueAt(fila, 0).toString();
                
                try (Connection conn = DatabaseManager.getConnection()) { // Obtiene la conexión                //---- AQUI
                    // Sentencia sql para obtener el id del colegio 
                    PreparedStatement st = conn.prepareStatement( 
                            "SELECT id_colegio FROM colegios WHERE nombre = ?" 
                    ); 
                    st.setString(1, nombreColegio); // Establece el valor del parámetro 
                    ResultSet resultado = st.executeQuery();
                    
                    System.out.println("SELECT id_colegio FROM colegios WHERE nombre="+nombreColegio);          //---- AQUI

                    if (resultado.next()) { 
                        int idColegio = resultado.getInt("id_colegio");
                    
                        // Sentencia sql para obtener la dirección del colegio 
                        PreparedStatement stDireccion = conn.prepareStatement( 
                            "SELECT * FROM colegios WHERE id_colegio = ?" 
                            ); 
                        stDireccion.setInt(1, idColegio); // Establece el valor del parámetro 
                        ResultSet resultadoDireccion = stDireccion.executeQuery(); 

                        if (resultadoDireccion.next()) { 
                            String direccionColegio = resultadoDireccion.getString("direccion"); 
                            System.out.println("Dirección del colegio: " + direccionColegio); 
                        } 
                    }
                } catch (SQLException e) {
                    Logger.getLogger(ListaColegios.class.getName()).log(Level.SEVERE, null, e);
                    System.out.println("Error al conectar o ejecutar consulta a la base de datos.");
                } catch (Exception e) {
                    Logger.getLogger(ListaColegios.class.getName()).log(Level.SEVERE, null, e);
                    System.out.println("Error inesperado: " + e.getMessage());
                }
            }else if(columna == 6) { 
                
            }
        }
    }//GEN-LAST:event_tablaColegiosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JTable tablaColegios;
    // End of variables declaration//GEN-END:variables
}
