/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tatamimanager.colegios;

import com.mycompany.tatamimanager.DatabaseManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author diana
 */
public class ListaColegios extends javax.swing.JPanel {

    
    DefaultTableModel modelo;

    /**
     * Creates new form ListaColegios
     */
    public ListaColegios() {
        initComponents();
            
        modelo = (DefaultTableModel) this.tablaColegios.getModel();
        
        try (Connection conn = DatabaseManager.getConnection()) { // Obtiene la conexión
            System.out.println("Connection created successfully");

            // Sentencias
            modelo.setRowCount(0);
            PreparedStatement st = conn.prepareStatement(
                "SELECT nombre, direccion, telefono, barrio, cod_postal FROM colegios"
            );
            ResultSet resultado = st.executeQuery();

            while (resultado.next()) {
                modelo.addRow(new Object[] {
                    resultado.getString("nombre"), 
                    resultado.getString("direccion"),
                    resultado.getInt("telefono"),
                    resultado.getString("barrio"),
                    resultado.getInt("cod_postal")
                });
            }
        } catch (SQLException e) {
            Logger.getLogger(ListaColegios.class.getName()).log(Level.SEVERE, null, e);
            System.out.println("Error al conectar o ejecutar consulta a la base de datos.");
        } catch (Exception e) {
            Logger.getLogger(ListaColegios.class.getName()).log(Level.SEVERE, null, e);
            System.out.println("Error inesperado: " + e.getMessage());
        }
        
        /*
        //ajustar tamaño columnas 
        tablaColegios.getColumnModel().getColumn(0).setPreferredWidth(70);
        tablaColegios.getColumnModel().getColumn(1).setPreferredWidth(70);
        tablaColegios.getColumnModel().getColumn(2).setPreferredWidth(5);
        tablaColegios.getColumnModel().getColumn(3).setPreferredWidth(30);
        tablaColegios.getColumnModel().getColumn(4).setPreferredWidth(10);
        */
        //tablaColegios.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);

        // Aplica el renderer solo a columnas Integer
        for (int col = 0; col < tablaColegios.getColumnCount(); col++) {
            if (tablaColegios.getColumnClass(col) == Integer.class) {
                tablaColegios.getColumnModel().getColumn(col).setCellRenderer(rightRenderer);
            }
        }
        
        //cierre de la conexión a la bbdd
        DatabaseManager.closeConnection();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaColegios = new javax.swing.JTable();
        lb_titulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tablaColegios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Dirección", "Teléfono", "Barrio", "Código Postal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaColegios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaColegios);
        if (tablaColegios.getColumnModel().getColumnCount() > 0) {
            tablaColegios.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablaColegios.getColumnModel().getColumn(1).setPreferredWidth(60);
            tablaColegios.getColumnModel().getColumn(2).setPreferredWidth(20);
            tablaColegios.getColumnModel().getColumn(3).setPreferredWidth(30);
            tablaColegios.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        lb_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_titulo.setText("Listado de Colegios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(lb_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lb_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JTable tablaColegios;
    // End of variables declaration//GEN-END:variables
}
