/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tatamimanager.Eventos;

import com.mycompany.tatamimanager.BBDD.DatabaseControlEventos;
import com.mycompany.tatamimanager.Inicio;
import com.mycompany.tatamimanager.Calendario.*;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author diana
 */
public class AddEventos extends javax.swing.JPanel {

    private String nombreEvento;
    private String descripcion;
    private String hora;
    private String lugar;
    private String fecha;
    
    /**
     * Creates new form AddEventos
     */
    public AddEventos() {
        initComponents();
    }

    
    public boolean validarDatos(){
        // Verificar si los campos están vacíos
        if (txt_nombre.getText().trim().isEmpty() || txArea_desc.getText().trim().isEmpty() || dateChooser_fecha.getDate() == null || 
            txt_hora.getText().trim().isEmpty() || txt_lugar.getText().trim().isEmpty()) {

            // Mostrar mensaje de advertencia
            JOptionPane.showMessageDialog(null, "Por favor, rellena todos los campos.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return false;
        } else {
            // Validar y asignar los valores
            
            nombreEvento = txt_nombre.getText().trim();
            descripcion = txArea_desc.getText().trim();
            hora = txt_hora.getText().trim();
            lugar = txt_lugar.getText().trim();

            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyy");
            fecha = formatoFecha.format(dateChooser_fecha.getDate() );
            
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser_fecha = new com.toedter.calendar.JDateChooser();
        lb_titulo = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        txt_lugar = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_hora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_GuardarEvento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txArea_desc = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 255, 255));

        lb_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_titulo.setText("Añadir Evento");

        lb_nombre.setText("Nombre del evento:");

        jLabel1.setText("Localización:");

        jLabel2.setText("Horario:");

        jLabel3.setText("Fecha:");

        btn_GuardarEvento.setBackground(new java.awt.Color(0, 102, 153));
        btn_GuardarEvento.setForeground(new java.awt.Color(255, 255, 255));
        btn_GuardarEvento.setText("Guardar Evento");
        btn_GuardarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarEventoActionPerformed(evt);
            }
        });

        jLabel4.setText("Descripción:");

        txArea_desc.setColumns(20);
        txArea_desc.setRows(5);
        jScrollPane1.setViewportView(txArea_desc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btn_GuardarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lb_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lb_nombre)
                            .addGap(36, 36, 36)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(73, 73, 73)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_lugar)
                                .addComponent(txt_hora)
                                .addComponent(dateChooser_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lb_titulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateChooser_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(48, 48, 48)
                .addComponent(btn_GuardarEvento)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GuardarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarEventoActionPerformed

        if (!validarDatos()) {
            return; // Si alguna validación falla, detener la ejecución
        }
        
        DatabaseControlEventos.guardarEventos(nombreEvento, descripcion, fecha, hora, lugar);
        /*
        if(!isUpdate){
            //si estoy añadiendo
            DatabaseControlEventos.guardarEventos(nombreEvento, descripcion, fecha, hora, lugar);
        }else{
            //si estoy modificando
            DataBaseControlColegios.editarColegio(nombreCole, direccionCole, telefonoCole, barrioCole, cpCole, id);
        }

        isUpdate = false; //volvemoa a establecer isUpdate como false
        */
        //cambiar panel a listaColegios
        JFrame frameInicio = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frameInicio instanceof Inicio) {
            ((Inicio) frameInicio).cambiarPanel(new VerCalendario());
        } 
    }//GEN-LAST:event_btn_GuardarEventoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GuardarEvento;
    private com.toedter.calendar.JDateChooser dateChooser_fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JTextArea txArea_desc;
    private javax.swing.JTextField txt_hora;
    private javax.swing.JTextField txt_lugar;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
